---
# file: site.yaml
- hosts: all
  roles:
    - base
    - common
    - storage
    - admin_users
    - workshop-user

- hosts: login_servers
  roles:
    - caddy

- hosts: workshop_servers
  roles:
    - docker
    - singularity
    - jupyter
    - biotools
    - cromwell
    - nextflow
    - rstudio
