---
# file: site.yaml

- hosts: all
  roles:
    - base
    - common
    - docker
    - storage
    - admin_users
    - workshop-user

    - singularity
    - nginx
    - jupyter
    - biotools
    - cromwell
    - nextflow
