---
- name: Create workshop users
  tags: workshop_users
  become: yes
  become_user: root
  block:
    - name: Create user
      user:
        name: "{{ item.username }}"
        password: "{{ item.password | password_hash('sha512') }}"
        shell: /bin/bash
        createhome: yes
        uid: "{{ item.uid }}"
        home: "/users/{{ item.username }}"
      with_items:
        - "{{ workshop_users }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Ensure homes are secure by default
      file:
        path: "/users/{{ item.username }}"
        mode: "u=rwx,g=,o="
      with_items:
        - "{{ workshop_users }}"
      loop_control:
        label: "{{ item.username }}"

    - name: Add user to 'docker' group
      when: docker_install is defined and docker_install
      user:
        name: "{{ item.username }}"
        groups: docker
        append: yes
      with_items:
        - "{{ workshop_users }}"
      loop_control:
        label: "{{ item.username }}"

    - name: 'Create jupyter_user group'
      when: jupyter_install is defined and jupyter_install
      group:
        name: jupyter_user
        state: present


    - name: Add user to 'jupyter_user' group
      when: jupyter_install is defined and jupyter_install
      user:
        name: "{{ item.username }}"
        groups: jupyter_user
        append: yes
      with_items:
        - "{{ workshop_users }}"
      loop_control:
        label: "{{ item.username }}"



    - name: Update SSH server configuration to allow password authentication
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        regexp: '^PasswordAuthentication.*'
        line: 'PasswordAuthentication yes'
        state: present
      notify: Restart SSH Service
      with_items:
        - /etc/ssh/sshd_config
        - /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
