---
# tasks file for roles/docker-compose

- name: Download docker-compose package
  ansible.builtin.shell: curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Change permissions
  ansible.builtin.shell: chmod +x /usr/local/bin/docker-compose
