---
# tasks file for roles/users
- name: Add groups
  group:
    name: "{{ item.username }}"
    state: present
    gid: "{{ item.uid }}"
  with_items:
    - "{{ users }}"
  retries: 5
  delay: 30

- name: Add users
  user:
    name: "{{ item.username }}"
    comment: "{{item.first_name}} {{item.last_name}}"
    state: present
    uid: "{{ item.uid }}"
    group: "{{ item.username }}"
    groups: "{{ item.username }}"
    append: yes
    home: "/home/{{ item.username }}"
    skeleton: /etc/skel
    generate_ssh_key: yes
    ssh_key_type: ed25519
    shell: /bin/bash
  with_items:
    - "{{ users }}"
  retries: 5
  delay: 30

- name: Set passwords from files
  authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "{{ item.ssh_public_key }}"
  with_items:
    - "{{ users }}"
  tags: "ssh_keys"

- name: Ensure homes are secure by default
  file:
    path: "/home/{{ item.username }}"
    mode: "u=rwx,g=,o="
  with_items:
    - "{{ users }}"

# Add all users to sudo and allow passwordless
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: /usr/sbin/visudo -cf %s
- name: Add sudoers users to wheel group
  user:
    name: "{{ item.username }}"
    groups: wheel
    append: yes
  with_items: "{{ users }}"
