---
- name: Common tasks
  tags:
    - common
  become: yes
  become_user: root
  block:
    - name: apt upgrade existing packages
      apt:
        upgrade: safe

    - name: apt Install Common Packages
      apt:
        name:
          - 'autoconf'
          - 'autofs'
          - 'build-essential'
          - 'curl'
          - 'dhcpcd5'
          - 'emacs-gtk'
          - 'fail2ban'
          - 'git'
          - 'gnutls-bin'
          - 'libbz2-dev'
          - 'libffi-dev'
          - 'libc6-dev'
          - 'libcurl4-openssl-dev'
          - 'libfuse3-dev'
          - 'libgdbm-dev'
          - 'libglib2.0-dev'
          - 'liblzma-dev'
          - 'libncurses-dev'
          - 'libreadline-dev'
          - 'libseccomp-dev'
          - 'libsqlite3-dev'
          - 'libssl-dev'
          - 'libtool-bin'
          - 'python-is-python3'
          - 'python3-pip'
          - 'python3-virtualenv'
          - 'sssd'
          - 'ssl-cert'
          - 'wget'
          - 'sqlite3'
          - 'unzip'

        state: latest
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success

    - name: apt remove unattended-upgrades
      apt:
        name:
          - 'unattended-upgrades'
        state: absent
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success

    - name: apt autoremove dependencies that are no longer required
      apt:
        autoremove: yes

- name: Install google cloud stuff
  tags: [gsutil]
  become: yes
  become_user: root
  block:
    - name: Add signed google cloud apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add google cloud apt repository
      apt_repository:
          repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
          state: present

    - name: Install google cloud cli
      apt:
        name:
          - google-cloud-cli
        state: latest
        update_cache: yes

- name: Install hosts file
  tags: [hosts]
  become: yes
  become_user: root
  block:
    - name: Copy hosts file
      copy:
          src: files/hosts
          dest: /etc/hosts
          owner: root
          group: root
          mode: 0644

- name: Install lmod and dependencies
  tags:
    - lmod
  block:
    - name: Install lmod dependencies
      become: yes
      apt:
        name:
          - lua5.3
          - lua-bit32:amd64
          - lua-posix:amd64
          - lua-posix-dev
          - liblua5.3-0:amd64
          - liblua5.3-dev:amd64
          - tcl
          - tcl-dev
          - tcl8.6
          - tcl8.6-dev:amd64
          - libtcl8.6:amd64
    - name: ensure src directory exists
      become: no
      file:
        path: ~/src
        state: directory

    - name: Fetch lmod source
      become: no
      get_url:
        url: "https://github.com/TACC/Lmod/archive/refs/tags/8.7.56.tar.gz"
        dest: ~/src/lmod.tar.gz
        checksum: "sha256:b7ee903b79ccd5bf195921f09bfc13879ad09d2b4598f4a0c2346bad9faaf28c"
    - name: Extract lmod source
      become: no
      unarchive:
        src: ~/src/lmod.tar.gz
        dest: ~/src
        creates: ~/src/Lmod-8.7.56
        remote_src: yes
    - name: Configure lmod
      become: no
      command: ./configure --prefix=/opt/lmod/8.7
      args:
        chdir: ~/src/Lmod-8.7.56
#        creates: ~/src/Lmod-8.7/makefile
    - name: Build lmod
      become: no
      command: make
      args:
        chdir: ~/src/Lmod-8.7.56
    - name: Install lmod
      become: yes
      command: make install
      args:
        chdir: "~{{ ansible_user }}/src/Lmod-8.7.56"
    - name: Link profile.d lmod.sh
      become: yes
      file:
        src: /opt/lmod/8.7/lmod/lmod/init/profile
        dest: /etc/profile.d/lmod.sh
        state: link
    - name: Add software/modules to MODULEPATH
      become: yes
      lineinfile:
          path: /etc/profile.d/lmod.sh
          line: "export MODULEPATH=/software/modules:$MODULEPATH"
          insertafter: EOF

#- name: Make sure python and java modules are loaded by default
#  tags: python_and_java
#  become: yes
#  lineinfile:
#    path: /etc/profile.d/lmod.sh
#    line: "module load python java"
#    insertafter: EOF
