---
- name: Common tasks
  tags:
    - common
  block:
    - name: apt upgrade existing packages
      apt:
        upgrade: safe

    - name: apt Install Common Packages
      apt:
        name:
          - 'autoconf'
          - 'autofs'
          - 'build-essential'
          - 'curl'
          - 'dhcpcd5'
          - 'emacs-gtk'
          - 'fail2ban'
          - 'git'
          - 'gnutls-bin'
          - 'libbz2-dev'
          - 'libfuse3-dev'
          - 'libglib2.0-dev'
          - 'liblzma-dev'
          - 'libncurses-dev'
          - 'libseccomp-dev'
          - 'libtool-bin'
          - 'python-is-python3'
          - 'python3-pip'
          - 'python3-virtualenv'
          - 'sssd'
          - 'ssl-cert'
          - 'wget'
          - 'sqlite3'
          - 'unzip'

        state: latest
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success

    - name: apt remove unattended-upgrades
      apt:
        name:
          - 'unattended-upgrades'
        state: absent
        update_cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success

    - name: apt autoremove dependencies that are no longer required
      apt:
        autoremove: yes

- name: Install google cloud stuff
  tags: [gsutil]
  block:
    - name: Add signed google cloud apt key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add google cloud apt repository
      apt_repository:
          repo: "deb https://packages.cloud.google.com/apt cloud-sdk main"
          state: present

    - name: Install google cloud cli
      apt:
        name:
          - google-cloud-cli
        state: latest
        update_cache: yes