---
# tasks file for roles/base

- name: Configure basic stuff
  tags:
    - base
  block:
    - name: Update timezone
      file:
        src: /usr/share/zoneinfo/{{ timezone }}
        dest: /etc/localtime
        state: link
      notify: update tzdata

    - name: Upgrade all existing packages
      apt:
        upgrade: dist
        update-cache: yes
      register: apt_res
      retries: 3
      delay: 15
      until: apt_res is success

    - name: Reboot the machine
      reboot:
        post_reboot_delay: 120
      when: reboot_after_update == "yes"

    - name: Ensure fail2ban is installed
      apt:
        name: fail2ban
        state: present
        update_cache: yes

    - name: Add fail2ban jail.local
      copy:
        src: ../templates/jail.local
        dest: /etc/fail2ban/
        owner: root
        group: root
        mode: 0644

    - name: start and enable service
      systemd:
        name: fail2ban
        state: started
        enabled: true
      tags:
        - configuration
        - fail2ban
        - fail2ban-start-enable-service
      when: ansible_service_mgr == 'systemd'

    - name: start and enable service
      service:
        name: fail2ban
        state: started
        enabled: true
      tags:
        - configuration
        - fail2ban
        - fail2ban-start-enable-service
      when: ansible_service_mgr != 'systemd'
