---
- name: Install bio tools
  tags: biotools
  when: biotools_install is defined and biotools_install
  become: yes
  become_user: root
  block:
    - name: Install samtools
      block:
        - name: Download samtools
          get_url:
            url: "https://github.com/samtools/samtools/releases/download/1.21/samtools-1.21.tar.bz2"
            checksum: "sha256:05724b083a6b6f0305fcae5243a056cc36cf826309c3cb9347a6b89ee3fc5ada"
            dest: "/tmp/samtools-1.21.tar.bz2"
        - name: Uncompress samtools
          unarchive:
            src: "/tmp/samtools-1.21.tar.bz2"
            dest: "/tmp/"
            remote_src: yes
            creates: "/tmp/samtools-1.21"
        - name: Configure samtools
          command: "./configure --prefix=/usr/local"
          args:
              chdir: "/tmp/samtools-1.21"
              creates: "/tmp/samtools-1.21/Makefile"
        - name: Build samtools
          command: "make"
          args:
              chdir: "/tmp/samtools-1.21"
              creates: "/tmp/samtools-1.21/samtools"
        - name: Install samtools
          command: "make install"
          args:
              chdir: "/tmp/samtools-1.21"
              creates: "/usr/local/bin/samtools"
    - name: Install bcftools
      block:
        - name: Download bcftools
          get_url:
            url: "https://github.com/samtools/bcftools/releases/download/1.21/bcftools-1.21.tar.bz2"
            checksum: "sha256:528a4cc1d3555368db75a700b22a3c95da893fd1827f6d304716dfd45ea4e282"
            dest: "/tmp/bcftools-1.21.tar.bz2"
        - name: Uncompress bcftools
          unarchive:
              src: "/tmp/bcftools-1.21.tar.bz2"
              dest: "/tmp/"
              remote_src: yes
              creates: "/tmp/bcftools-1.21"
        - name: Configure bcftools
          command: "./configure --prefix=/usr/local"
          args:
              chdir: "/tmp/bcftools-1.21"
              creates: "/tmp/bcftools-1.21/Makefile"
        - name: Build bcftools
          command: "make"
          args:
              chdir: "/tmp/bcftools-1.21"
              creates: "/tmp/bcftools-1.21/bcftools"
        - name: Install bcftools
          command: "make install"
          args:
              chdir: "/tmp/bcftools-1.21"
              creates: "/usr/local/bin/bcftools"
    - name: Install htslib
      block:
        - name: Download htslib
          get_url:
            url: "https://github.com/samtools/htslib/releases/download/1.21/htslib-1.21.tar.bz2"
            checksum: "sha256:84b510e735f4963641f26fd88c8abdee81ff4cb62168310ae716636aac0f1823"
            dest: "/tmp/htslib-1.21.tar.bz2"
        - name: Uncompress htslib
          unarchive:
            src: "/tmp/htslib-1.21.tar.bz2"
            dest: "/tmp/"
            remote_src: yes
            creates: "/tmp/htslib-1.21"
        - name: Configure htslib
          command: "./configure --prefix=/usr/local"
          args:
            chdir: "/tmp/htslib-1.21"
            creates: "/tmp/htslib-1.21/Makefile"
        - name: Build htslib
          command: "make"
          args:
            chdir: "/tmp/htslib-1.21"
            creates: "/tmp/htslib-1.21/tabix"
        - name: Install htslib
          command: "make install"
          args:
            chdir: "/tmp/htslib-1.21"
            creates: "/usr/local/bin/tabix"
    - name: Install gatk
      block:
        - name: Download gatk source
          get_url:
            url: https://github.com/broadinstitute/gatk/releases/download/4.6.1.0/gatk-4.6.1.0.zip
            checksum: "sha256:ac7015c3f0ef1852745ca0ef647adbf8ddef5db63ab485b00bc1ffe654814155"
            dest: /opt/gatk-4.6.1.0.zip
            mode: '0644'

        - name: Extract gatk source
          unarchive:
            src: /opt/gatk-4.6.1.0.zip
            dest: /opt/
            remote_src: yes
            creates: /opt/gatk-4.6.1.0

        - name: Create a symlink from /opt/gatk-4.6.1.0/gatk to /usr/local/bin
          file:
            src: /opt/gatk-4.6.1.0/gatk
            dest: /usr/local/bin/gatk
            state: link
    - name: Install picard
      block:
        - name: Download picard
          get_url:
            url: https://github.com/broadinstitute/picard/releases/download/3.3.0/picard.jar
            dest: /usr/local/share/picard.jar
            owner: root
            group: root
            mode: '0644'

        - name: Create a script to run Picard JAR
          copy:
            src: picard  # Template file
            dest: /usr/local/bin/picard
            mode: '0755'

